name: Build and Push Angular Docker Image

on:
  push:
    branches:
      - dockerfileTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 設定 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 列出所有目錄和檔案
        run: ls -R
      - name: 安裝 Angular 依賴並建構
        run: |
          npm install -g @angular/cli
          npm install
          ng build --configuration=production

      - name: 登入 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 建立 Docker 映像
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/DeshiiWeb:latest .

      - name: 推送到 Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/DeshiiWeb:latest
